//! MMC Core Library - Unified API for all platforms
//!
//! This crate provides a unified interface for device discovery, pairing,
//! file transfer, and remote control across Android, iOS, and PC platforms.
//!
//! ## Architecture
//!
//! The core logic is implemented in pure Rust. For cross-platform bindings,
//! UniFFI can be used to generate Android (JNI) and iOS (Swift) bindings from
//! the Rust source using the UDL file at `src/mmc_core.udl`.
//!
//! ## Usage
//!
//! ```
//! use mmc_core::MmcCore;
//! use mmc_core::{CoreConfig, DeviceType};
//!
//! let core = MmcCore::new();
//! let config = CoreConfig {
//!     device_id: "my-device".to_string(),
//!     device_name: "My Device".to_string(),
//!     device_type: DeviceType::Phone,
//!     app_version: "1.0.0".to_string(),
//!     log_dir: None,
//! };
//! let _ = core.init(config);
//! ```

pub mod core;
pub mod error;
pub mod types;

pub use core::MmcCore;
pub use error::{CoreError, Result};
pub use types::*;

// Include UniFFI generated scaffolding (or stub if generation fails)
// The scaffolding is generated by build.rs
include!(concat!(env!("OUT_DIR"), "/mmc_core.uniffi.rs"));

// --- Android JNI Support ---
// Android runtime will call JNI_OnLoad when loading the .so library.
// We provide a minimal, dependency-free implementation so the library
// can be loaded successfully without requiring external JNI crates.

pub mod android;

#[cfg(target_os = "android")]
#[no_mangle]
pub extern "system" fn JNI_OnLoad(
    _vm: *mut std::os::raw::c_void,
    _reserved: *mut std::os::raw::c_void,
) -> i32 {
    // JNI_VERSION_1_6 = 0x00010006
    0x00010006
}

#[cfg(target_os = "android")]
#[no_mangle]
pub extern "system" fn JNI_OnUnload(
    _vm: *mut std::os::raw::c_void,
    _reserved: *mut std::os::raw::c_void,
) {
    // Cleanup hook - currently no-op
}
