// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceInfo {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device_name: ::prost::alloc::string::String,
    #[prost(enumeration = "DeviceType", tag = "3")]
    pub device_type: i32,
    #[prost(string, tag = "4")]
    pub os_version: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub app_version: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub port: u32,
    #[prost(string, tag = "8")]
    pub public_key_fingerprint: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub capabilities: ::core::option::Option<Capabilities>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Capabilities {
    #[prost(bool, tag = "1")]
    pub file_transfer: bool,
    #[prost(bool, tag = "2")]
    pub screen_mirror: bool,
    #[prost(bool, tag = "3")]
    pub remote_control: bool,
    #[prost(bool, tag = "4")]
    pub clipboard_sync: bool,
}
/// ============================================================
/// Pairing Protocol
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PairingRequest {
    #[prost(string, tag = "1")]
    pub pairing_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub device_info: ::core::option::Option<DeviceInfo>,
    #[prost(message, optional, tag = "3")]
    pub requested_capabilities: ::core::option::Option<Capabilities>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PairingResponse {
    #[prost(string, tag = "1")]
    pub pairing_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub accepted: bool,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub granted_capabilities: ::core::option::Option<Capabilities>,
}
/// ============================================================
/// File Transfer Protocol
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileManifestRequest {
    #[prost(string, tag = "1")]
    pub file_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub file_name: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub total_size: i64,
    #[prost(string, tag = "4")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub chunk_size: i32,
    #[prost(int32, tag = "6")]
    pub total_chunks: i32,
    #[prost(message, repeated, tag = "7")]
    pub chunks: ::prost::alloc::vec::Vec<ChunkInfo>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChunkInfo {
    #[prost(int32, tag = "1")]
    pub index: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub blake3_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "3")]
    pub size: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileManifestResponse {
    #[prost(string, tag = "1")]
    pub file_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub accepted: bool,
    #[prost(int32, repeated, tag = "3")]
    pub already_have_chunks: ::prost::alloc::vec::Vec<i32>,
    #[prost(enumeration = "TransferErrorReason", tag = "4")]
    pub error_reason: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferError {
    #[prost(string, tag = "1")]
    pub file_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub error_code: i32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// ============================================================
/// Remote Control Protocol
/// ============================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TouchEvent {
    #[prost(uint64, tag = "1")]
    pub sequence_id: u64,
    #[prost(uint64, tag = "2")]
    pub timestamp_ms: u64,
    #[prost(enumeration = "TouchType", tag = "3")]
    pub r#type: i32,
    #[prost(float, tag = "4")]
    pub x: f32,
    #[prost(float, tag = "5")]
    pub y: f32,
    #[prost(float, tag = "6")]
    pub pressure: f32,
    #[prost(float, tag = "7")]
    pub touch_major: f32,
    #[prost(int32, tag = "8")]
    pub pointer_id: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyEvent {
    #[prost(uint64, tag = "1")]
    pub sequence_id: u64,
    #[prost(uint64, tag = "2")]
    pub timestamp_ms: u64,
    #[prost(enumeration = "KeyEventType", tag = "3")]
    pub r#type: i32,
    #[prost(int32, tag = "4")]
    pub key_code: i32,
    #[prost(string, tag = "5")]
    pub text: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClipboardContent {
    #[prost(uint64, tag = "1")]
    pub timestamp_ms: u64,
    #[prost(oneof = "clipboard_content::Content", tags = "2, 3, 4")]
    pub content: ::core::option::Option<clipboard_content::Content>,
}
/// Nested message and enum types in `ClipboardContent`.
pub mod clipboard_content {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Content {
        #[prost(string, tag = "2")]
        Text(::prost::alloc::string::String),
        #[prost(bytes, tag = "3")]
        ImagePng(::prost::alloc::vec::Vec<u8>),
        #[prost(string, tag = "4")]
        Url(::prost::alloc::string::String),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeviceType {
    Unknown = 0,
    Phone = 1,
    Tablet = 2,
    Pc = 3,
    Tv = 4,
    Wearable = 5,
}
impl DeviceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            DeviceType::Unknown => "UNKNOWN",
            DeviceType::Phone => "PHONE",
            DeviceType::Tablet => "TABLET",
            DeviceType::Pc => "PC",
            DeviceType::Tv => "TV",
            DeviceType::Wearable => "WEARABLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "PHONE" => Some(Self::Phone),
            "TABLET" => Some(Self::Tablet),
            "PC" => Some(Self::Pc),
            "TV" => Some(Self::Tv),
            "WEARABLE" => Some(Self::Wearable),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TransferErrorReason {
    None = 0,
    DiskFull = 1,
    PermissionDenied = 2,
    UnsupportedType = 3,
    SizeLimitExceeded = 4,
}
impl TransferErrorReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TransferErrorReason::None => "NONE",
            TransferErrorReason::DiskFull => "DISK_FULL",
            TransferErrorReason::PermissionDenied => "PERMISSION_DENIED",
            TransferErrorReason::UnsupportedType => "UNSUPPORTED_TYPE",
            TransferErrorReason::SizeLimitExceeded => "SIZE_LIMIT_EXCEEDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NONE" => Some(Self::None),
            "DISK_FULL" => Some(Self::DiskFull),
            "PERMISSION_DENIED" => Some(Self::PermissionDenied),
            "UNSUPPORTED_TYPE" => Some(Self::UnsupportedType),
            "SIZE_LIMIT_EXCEEDED" => Some(Self::SizeLimitExceeded),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TouchType {
    TouchUnknown = 0,
    TouchDown = 1,
    TouchMove = 2,
    TouchUp = 3,
    TouchCancel = 4,
}
impl TouchType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TouchType::TouchUnknown => "TOUCH_UNKNOWN",
            TouchType::TouchDown => "TOUCH_DOWN",
            TouchType::TouchMove => "TOUCH_MOVE",
            TouchType::TouchUp => "TOUCH_UP",
            TouchType::TouchCancel => "TOUCH_CANCEL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TOUCH_UNKNOWN" => Some(Self::TouchUnknown),
            "TOUCH_DOWN" => Some(Self::TouchDown),
            "TOUCH_MOVE" => Some(Self::TouchMove),
            "TOUCH_UP" => Some(Self::TouchUp),
            "TOUCH_CANCEL" => Some(Self::TouchCancel),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum KeyEventType {
    KeyUnknown = 0,
    KeyDown = 1,
    KeyUp = 2,
    KeyText = 3,
}
impl KeyEventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            KeyEventType::KeyUnknown => "KEY_UNKNOWN",
            KeyEventType::KeyDown => "KEY_DOWN",
            KeyEventType::KeyUp => "KEY_UP",
            KeyEventType::KeyText => "KEY_TEXT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "KEY_UNKNOWN" => Some(Self::KeyUnknown),
            "KEY_DOWN" => Some(Self::KeyDown),
            "KEY_UP" => Some(Self::KeyUp),
            "KEY_TEXT" => Some(Self::KeyText),
            _ => None,
        }
    }
}
